name: Chain types
on:
  schedule:
    - cron:  '30 0/12 * * *'

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: check
      env:
        CI_LOG: 123
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ci:chainTypes

    - name: issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@e27dddc79c92bc6e4562f268fffa5ed752639abd
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT_BOT }}
      with:
        filename: .github/chain-types.md
        update_existing: true
