name: Chain endpoints
on:
  schedule:
    - cron:  '50 0/12 * * *'

jobs:
  types:
    if: (github.event_name == 'schedule' && github.repository == 'polkadot-js/apps') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: check
      env:
        CI_LOG: 123
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ci:chainEndpoints

    - name: issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@e27dddc79c92bc6e4562f268fffa5ed752639abd
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT_BOT }}
      with:
        filename: .github/chain-endpoints.md
        update_existing: true
